### PR TITLE
updated game menu to indicate Difficulty level.

### PR DESCRIPTION
**Pull request by CristinaRuth**
Also updated numbers to words to for easier readability.

### CODE REVIEW

**Comment by skotz** [comment]
Thanks! I like this. 

I think we need to address the styles of the "new game" interface. The "medium" string is a bit large. Maybe reduce the .new-game font size to 24px and remove the uppercase transform...

image

Ref: #8

**Comment by CristinaRuth** [comment]
k :)

**Comment by skotz** [comment]
👍

**Comment by CristinaRuth** [comment]
Woootz

**Pull request merged**
